import type { Metadata } from 'next'
import Link from 'next/link'
import { Logo } from '@/components/ui/Logo'

export const metadata: Metadata = {
  title: 'Terms of Service — LYCHO',
  description: 'Terms of Service for LYCHO AI agent platform.',
}

export default function TermsPage() {
  return (
    <div style={{ background: '#070707', minHeight: '100vh', color: '#F0EBE1' }}>
      <nav
        className="sticky top-0 z-50 px-6 py-4 flex items-center justify-between"
        style={{ background: 'rgba(7,7,7,0.95)', borderBottom: '1px solid #2a2a2a', backdropFilter: 'blur(12px)' }}
      >
        <Link href="/"><Logo size="sm" /></Link>
        <Link href="/signup" className="text-sm font-sans px-4 py-2 rounded transition-colors"
          style={{ background: 'rgba(201,168,76,0.1)', color: '#C9A84C', border: '1px solid rgba(201,168,76,0.3)' }}>
          Get Started
        </Link>
      </nav>

      <div className="max-w-3xl mx-auto px-5 lg:px-8 py-16">
        <p className="text-xs font-sans uppercase tracking-[0.3em] mb-2" style={{ color: '#7a6130' }}>Legal</p>
        <h1 className="font-bebas text-5xl tracking-[0.15em] mb-2" style={{ color: '#C9A84C' }}>Terms of Service</h1>
        <p className="text-sm font-sans mb-12" style={{ color: '#6b6b6b' }}>Last updated: April 3, 2026</p>

        <div className="space-y-10">
          <section>
            <h2 className="font-bebas text-2xl tracking-[0.1em] mb-3" style={{ color: '#F0EBE1' }}>1. Acceptance of Terms</h2>
            <p className="text-sm font-sans leading-relaxed" style={{ color: '#6b6b6b' }}>
              By accessing or using LYCHO (&quot;the Platform&quot;, &quot;we&quot;, &quot;us&quot;, &quot;our&quot;), you agree to be bound by these Terms of Service.
              If you do not agree to these terms, do not use the Platform.
            </p>
          </section>

          <section>
            <h2 className="font-bebas text-2xl tracking-[0.1em] mb-3" style={{ color: '#F0EBE1' }}>2. Description of Service</h2>
            <p className="text-sm font-sans leading-relaxed" style={{ color: '#6b6b6b' }}>
              LYCHO provides an AI-powered agent platform that enables businesses to deploy intelligent agents
              across multiple communication channels including WhatsApp, Telegram, email, web widgets, and more.
              The service includes agent management, conversation handling, analytics, and automation features.
            </p>
          </section>

          <section>
            <h2 className="font-bebas text-2xl tracking-[0.1em] mb-3" style={{ color: '#F0EBE1' }}>3. Account Registration</h2>
            <p className="text-sm font-sans leading-relaxed" style={{ color: '#6b6b6b' }}>
              You must provide accurate and complete information when registering an account.
              You are responsible for maintaining the security of your account credentials.
              You must be at least 18 years old and authorized to bind your business to these terms.
            </p>
          </section>

          <section>
            <h2 className="font-bebas text-2xl tracking-[0.1em] mb-3" style={{ color: '#F0EBE1' }}>4. Acceptable Use</h2>
            <p className="text-sm font-sans leading-relaxed" style={{ color: '#6b6b6b' }}>
              You agree not to use the Platform to: (a) send spam or unsolicited messages; (b) distribute malware;
              (c) violate any applicable laws or regulations; (d) impersonate another person or entity;
              (e) attempt to gain unauthorized access to the Platform or other users&apos; data;
              (f) use the Platform for any illegal or harmful purpose.
            </p>
          </section>

          <section>
            <h2 className="font-bebas text-2xl tracking-[0.1em] mb-3" style={{ color: '#F0EBE1' }}>5. Data and Privacy</h2>
            <p className="text-sm font-sans leading-relaxed" style={{ color: '#6b6b6b' }}>
              We collect and process data as described in our Privacy Policy. You retain ownership of your data.
              We process conversation data to provide AI-powered responses and improve our services.
              We implement industry-standard security measures to protect your data.
            </p>
          </section>

          <section>
            <h2 className="font-bebas text-2xl tracking-[0.1em] mb-3" style={{ color: '#F0EBE1' }}>6. Intellectual Property</h2>
            <p className="text-sm font-sans leading-relaxed" style={{ color: '#6b6b6b' }}>
              The Platform, including its software, design, branding, and AI models, is the intellectual property of LYCHO Systems.
              Your use of the Platform does not grant you any ownership rights.
              Content generated by AI agents on your behalf belongs to you.
            </p>
          </section>

          <section>
            <h2 className="font-bebas text-2xl tracking-[0.1em] mb-3" style={{ color: '#F0EBE1' }}>7. Trial and Paid Plans</h2>
            <p className="text-sm font-sans leading-relaxed" style={{ color: '#6b6b6b' }}>
              New users receive a free trial period. After the trial expires, you must subscribe to a paid plan
              to continue using the Platform. Pricing is as stated on our pricing page. We may change pricing
              with 30 days&apos; notice. Refunds are handled on a case-by-case basis.
            </p>
          </section>

          <section>
            <h2 className="font-bebas text-2xl tracking-[0.1em] mb-3" style={{ color: '#F0EBE1' }}>8. Service Availability</h2>
            <p className="text-sm font-sans leading-relaxed" style={{ color: '#6b6b6b' }}>
              We aim for 99.9% uptime but do not guarantee uninterrupted service. Scheduled maintenance
              will be communicated in advance. We are not liable for temporary service interruptions
              caused by factors beyond our reasonable control.
            </p>
          </section>

          <section>
            <h2 className="font-bebas text-2xl tracking-[0.1em] mb-3" style={{ color: '#F0EBE1' }}>9. Limitation of Liability</h2>
            <p className="text-sm font-sans leading-relaxed" style={{ color: '#6b6b6b' }}>
              LYCHO shall not be liable for any indirect, incidental, special, consequential, or punitive damages
              arising from your use of the Platform. Our total liability shall not exceed the amount you paid
              us in the 12 months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="font-bebas text-2xl tracking-[0.1em] mb-3" style={{ color: '#F0EBE1' }}>10. Termination</h2>
            <p className="text-sm font-sans leading-relaxed" style={{ color: '#6b6b6b' }}>
              Either party may terminate this agreement at any time. Upon termination, your access to the Platform
              will cease. We will retain your data for 30 days after termination, after which it will be permanently deleted.
            </p>
          </section>

          <section>
            <h2 className="font-bebas text-2xl tracking-[0.1em] mb-3" style={{ color: '#F0EBE1' }}>11. Governing Law</h2>
            <p className="text-sm font-sans leading-relaxed" style={{ color: '#6b6b6b' }}>
              These terms are governed by the laws of Pakistan. Any disputes shall be resolved in the courts of Lahore, Pakistan.
            </p>
          </section>

          <section>
            <h2 className="font-bebas text-2xl tracking-[0.1em] mb-3" style={{ color: '#F0EBE1' }}>12. Contact</h2>
            <p className="text-sm font-sans leading-relaxed" style={{ color: '#6b6b6b' }}>
              For questions about these terms, contact us at <a href="mailto:hello@lycho.app" style={{ color: '#C9A84C' }}>hello@lycho.app</a>.
            </p>
          </section>
        </div>

        <div className="mt-16 pt-8" style={{ borderTop: '1px solid #2a2a2a' }}>
          <div className="flex flex-wrap gap-4">
            <Link href="/privacy" className="text-sm font-sans" style={{ color: '#C9A84C' }}>Privacy Policy</Link>
            <Link href="/" className="text-sm font-sans" style={{ color: '#6b6b6b' }}>Home</Link>
            <Link href="/signup" className="text-sm font-sans" style={{ color: '#6b6b6b' }}>Sign Up</Link>
          </div>
        </div>
      </div>
    </div>
  )
}
