export interface CountryProfile {
  country_code: string
  country_name: string
  currency: string
  primary_language: string
  secondary_languages: string[]
  timezone: string
  regulatory_context: string
  market_context: string
  agent_injection: string
}

export const COUNTRY_PROFILES: CountryProfile[] = [
  {
    country_code: 'PK',
    country_name: 'Pakistan',
    currency: 'PKR',
    primary_language: 'Urdu',
    secondary_languages: ['English', 'Punjabi', 'Sindhi', 'Pashto'],
    timezone: 'Asia/Karachi',
    regulatory_context: `Tax: FBR (Federal Board of Revenue). NTN required for all businesses. Sales tax registration via STRN. Tax year: July 1 - June 30. Income tax return deadline: September 30. Sales tax return: monthly by 18th. Corporate: SECP (Securities and Exchange Commission of Pakistan). Banking: SBP (State Bank of Pakistan). Labour: EOBI (Employees Old-Age Benefits Institution). Import/Export: Pakistan Customs, Ministry of Commerce.`,
    market_context: `Major cities: Karachi (financial hub), Lahore (commercial centre), Islamabad (capital), Faisalabad (industrial), Rawalpindi. Payment methods: JazzCash, EasyPaisa, SadaPay, NayaPay, bank transfer, cash. Key industries: Textiles, IT services, agriculture, pharmaceuticals, construction. Business culture: relationship-driven, hierarchical, family business dominant. Seasonal patterns: Ramadan (slow retail, high food), Eid (massive retail surge), summer heat affects productivity.`,
    agent_injection: `You are operating in Pakistan. Currency: PKR. Primary language: Urdu (respond in Urdu if customer uses Urdu, English if English). Tax authority: FBR. Payment methods: JazzCash, EasyPaisa, SadaPay. Business culture: respectful, relationship-first. Key dates: Eid ul-Fitr, Eid ul-Adha, Pakistan Day, Independence Day affect business operations.`
  },
  {
    country_code: 'AE',
    country_name: 'United Arab Emirates',
    currency: 'AED',
    primary_language: 'Arabic',
    secondary_languages: ['English', 'Hindi', 'Urdu'],
    timezone: 'Asia/Dubai',
    regulatory_context: `Tax: FTA (Federal Tax Authority). VAT 5%. Corporate tax 9% (from 2023). Free zone companies have tax benefits. Corporate: UAE Companies Law. Ministry of Economy for mainland. Free Zone Authorities for DIFC, ADGM, JAFZA etc. Banking: UAE Central Bank. Labour: Ministry of Human Resources and Emiratisation (MOHRE). Emiratisation quotas apply.`,
    market_context: `Major cities: Dubai (global business hub), Abu Dhabi (capital, oil wealth), Sharjah, Ajman. Payment methods: Credit cards, Apple Pay, Samsung Pay, bank transfer, cash still used. Key industries: Real estate, tourism, finance, logistics, technology. Business culture: formal initially, relationship-driven, respect for hierarchy. Weekend: Saturday-Sunday. Working hours: 9am-6pm. Ramadan: shorter working hours legally required.`,
    agent_injection: `You are operating in the UAE. Currency: AED. Languages: Arabic and English equally. Tax: VAT 5% applies. Free zone or mainland matters for regulations. Emiratisation is a key business compliance issue. Business culture: formal, professional. Weekend is Saturday-Sunday. Ramadan hours are legally reduced.`
  },
  {
    country_code: 'SA',
    country_name: 'Saudi Arabia',
    currency: 'SAR',
    primary_language: 'Arabic',
    secondary_languages: ['English'],
    timezone: 'Asia/Riyadh',
    regulatory_context: `Tax: ZATCA (Zakat, Tax and Customs Authority). VAT 15%. Zakat for Saudi entities. e-Invoicing (FATOORA) mandatory. Corporate: Ministry of Commerce. Vision 2030 compliance important. Banking: Saudi Central Bank (SAMA). Labour: Ministry of Human Resources. Saudisation (Nitaqat) quotas mandatory. GOSI for social insurance.`,
    market_context: `Major cities: Riyadh (capital), Jeddah (commercial), Dammam, Mecca, Medina. Payment methods: mada (national network), STC Pay, Apple Pay, credit cards. Key industries: Oil, construction, retail, healthcare, tourism (Vision 2030 focus). Business culture: highly formal, gender-separated in traditional settings, Vision 2030 modernising rapidly. Friday is holy day — no business. Ramadan is critical.`,
    agent_injection: `You are operating in Saudi Arabia. Currency: SAR. Language: Arabic primarily, English for business. Tax: ZATCA, VAT 15%, Zakat. e-Invoicing mandatory. Saudisation quotas are a compliance priority. Vision 2030 drives business transformation. Friday is the holy day. Ramadan significantly affects all business operations. Highly formal business culture.`
  },
  {
    country_code: 'GB',
    country_name: 'United Kingdom',
    currency: 'GBP',
    primary_language: 'English',
    secondary_languages: ['Welsh', 'Scottish Gaelic'],
    timezone: 'Europe/London',
    regulatory_context: `Tax: HMRC. Corporation tax 25%. VAT 20% (standard). Self-assessment for self-employed. PAYE for employees. Corporate: Companies House registration. FCA for financial services. ICO for data protection (UK GDPR). Employment: ACAS guidelines, minimum wage, statutory rights. Import/Export: post-Brexit customs apply.`,
    market_context: `Major cities: London (global financial hub), Manchester, Birmingham, Edinburgh, Leeds. Payment methods: bank transfer (Faster Payments), credit/debit cards, PayPal, Wise. Key industries: Finance, professional services, technology, retail, manufacturing. Business culture: professional, punctual, understated, email-first. Working hours: 9-5:30pm typically.`,
    agent_injection: `You are operating in the United Kingdom. Currency: GBP. Language: English. Tax authority: HMRC. Corporation tax 25%, VAT 20%. Companies House registration required. UK GDPR data protection applies. Post-Brexit customs rules for imports/exports. Professional, punctual business culture.`
  },
  {
    country_code: 'US',
    country_name: 'United States',
    currency: 'USD',
    primary_language: 'English',
    secondary_languages: ['Spanish'],
    timezone: 'Multiple — ask client',
    regulatory_context: `Tax: IRS. Federal + state taxes. EIN required. Sales tax varies by state. Corporate: State-level incorporation (Delaware popular). SEC for public companies. FINRA for financial services. FTC for consumer protection. HIPAA for healthcare. SOX for public companies. Employment: federal minimum wage + state variations.`,
    market_context: `Major cities: New York, Los Angeles, Chicago, Houston, Phoenix. Payment methods: Credit/debit cards dominant, ACH transfers, PayPal, Venmo, Zelle, Stripe. Key industries: Technology, finance, healthcare, retail, manufacturing. Business culture: direct, fast-paced, results-oriented, first-name basis. Multiple time zones important.`,
    agent_injection: `You are operating in the United States. Currency: USD. Language: English (Spanish secondary). Tax: IRS, federal + state. EIN required. Sales tax varies by state. Multiple time zones — confirm client timezone. Direct, results-focused business culture. Data privacy varies by state (CCPA in California).`
  },
  {
    country_code: 'CA',
    country_name: 'Canada',
    currency: 'CAD',
    primary_language: 'English',
    secondary_languages: ['French'],
    timezone: 'Multiple — ask client',
    regulatory_context: `Tax: CRA (Canada Revenue Agency). GST/HST. Corporate: federal or provincial incorporation. PIPEDA for privacy. Employment: provincial labour standards. French language laws in Quebec.`,
    market_context: `Major cities: Toronto, Vancouver, Montreal, Calgary, Ottawa. Payment methods: Interac, credit cards, e-Transfer. Key industries: Finance, natural resources, technology, healthcare. Business culture: polite, multicultural, bilingual in Quebec.`,
    agent_injection: `You are operating in Canada. Currency: CAD. Languages: English and French (Quebec). Tax: CRA, GST/HST. PIPEDA privacy law applies. Provincial regulations vary. Bilingual requirements in Quebec. Polite, multicultural business culture.`
  },
  {
    country_code: 'AU',
    country_name: 'Australia',
    currency: 'AUD',
    primary_language: 'English',
    secondary_languages: [],
    timezone: 'Multiple — ask client',
    regulatory_context: `Tax: ATO (Australian Tax Office). GST 10%. Company tax 25-30%. ABN required. Corporate: ASIC. Employment: Fair Work Act, minimum wage, award rates. Privacy: Australian Privacy Act.`,
    market_context: `Major cities: Sydney, Melbourne, Brisbane, Perth, Adelaide. Payment methods: EFTPOS, credit cards, PayID, bank transfer. Key industries: Mining, finance, agriculture, technology, tourism. Business culture: casual, direct, egalitarian.`,
    agent_injection: `You are operating in Australia. Currency: AUD. Language: English. Tax: ATO, GST 10%. ABN required. ASIC for corporate compliance. Fair Work Act for employment. Casual, direct business culture.`
  },
  { country_code: 'IN', country_name: 'India', currency: 'INR', primary_language: 'Hindi', secondary_languages: ['English', 'Tamil', 'Telugu', 'Bengali'], timezone: 'Asia/Kolkata', regulatory_context: 'Tax: Income Tax Act, GST 18% standard. Corporate: MCA, Companies Act 2013. SEBI for capital markets. RBI for banking. FSSAI for food.', market_context: 'Major cities: Mumbai, Delhi, Bangalore, Chennai, Hyderabad. UPI payments dominant. IT sector, manufacturing, agriculture, services.', agent_injection: 'Operating in India. Currency INR. GST applies. UPI, Paytm, PhonePe are primary payments. Diverse languages — detect and respond accordingly. Formal business culture.' },
  { country_code: 'NG', country_name: 'Nigeria', currency: 'NGN', primary_language: 'English', secondary_languages: ['Yoruba', 'Igbo', 'Hausa'], timezone: 'Africa/Lagos', regulatory_context: 'Tax: FIRS. VAT 7.5%. Corporate: CAC registration. CBN for banking. NAFDAC for food/drugs.', market_context: 'Lagos financial hub. Mobile money, bank transfers. Oil, agriculture, fintech, entertainment sectors.', agent_injection: 'Operating in Nigeria. Currency NGN. Business culture relationship-driven. Mobile money common. English business language.' },
  { country_code: 'EG', country_name: 'Egypt', currency: 'EGP', primary_language: 'Arabic', secondary_languages: ['English'], timezone: 'Africa/Cairo', regulatory_context: 'Tax: ETA. VAT 14%. Corporate: GAFI registration. CBE for banking.', market_context: 'Cairo hub. Tourism, Suez Canal, agriculture, manufacturing. Cash still dominant but digital growing.', agent_injection: 'Operating in Egypt. Currency EGP. Arabic primary. Formal business culture. Ramadan affects operations significantly.' },
  { country_code: 'KE', country_name: 'Kenya', currency: 'KES', primary_language: 'English', secondary_languages: ['Swahili'], timezone: 'Africa/Nairobi', regulatory_context: 'Tax: KRA. VAT 16%. Corporate: Registrar of Companies. CBK for banking.', market_context: 'Nairobi hub. M-Pesa mobile money dominant. Agriculture, fintech, tourism, tech hub of East Africa.', agent_injection: 'Operating in Kenya. Currency KES. M-Pesa is primary payment. English and Swahili both used. Tech-forward market.' },
  { country_code: 'ZA', country_name: 'South Africa', currency: 'ZAR', primary_language: 'English', secondary_languages: ['Zulu', 'Xhosa', 'Afrikaans'], timezone: 'Africa/Johannesburg', regulatory_context: 'Tax: SARS. VAT 15%. Corporate: CIPC. SARB for banking. BEE compliance important.', market_context: 'Johannesburg financial hub. Mining, finance, retail, agriculture. Card payments and EFT common.', agent_injection: 'Operating in South Africa. Currency ZAR. BBBEE compliance matters for business. Formal English business culture.' },
  { country_code: 'TR', country_name: 'Turkey', currency: 'TRY', primary_language: 'Turkish', secondary_languages: ['English'], timezone: 'Europe/Istanbul', regulatory_context: 'Tax: Revenue Administration. VAT 20% standard. Corporate: Trade Registry. BDDK for banking.', market_context: 'Istanbul hub. Manufacturing, tourism, agriculture, textiles. Growing e-commerce. Card and bank transfer common.', agent_injection: 'Operating in Turkey. Currency TRY. Turkish primary language. Formal business culture. EU candidate country — some EU regulations apply.' },
  { country_code: 'ID', country_name: 'Indonesia', currency: 'IDR', primary_language: 'Bahasa Indonesia', secondary_languages: ['English', 'Javanese'], timezone: 'Asia/Jakarta', regulatory_context: 'Tax: DGT. VAT 11%. Corporate: OSS registration. OJK for financial services.', market_context: 'Jakarta hub. Agriculture, manufacturing, digital economy booming. GoPay, OVO, DANA mobile payments.', agent_injection: 'Operating in Indonesia. Currency IDR. Bahasa Indonesia primary. Relationship-driven business culture. Mobile payments dominant.' },
  { country_code: 'MY', country_name: 'Malaysia', currency: 'MYR', primary_language: 'Bahasa Malaysia', secondary_languages: ['English', 'Mandarin', 'Tamil'], timezone: 'Asia/Kuala_Lumpur', regulatory_context: 'Tax: LHDN. SST 6-10%. Corporate: SSM. BNM for banking.', market_context: 'KL hub. Manufacturing, palm oil, digital economy, Islamic finance. DuitNow, FPX payments.', agent_injection: 'Operating in Malaysia. Currency MYR. Multilingual — English widely used in business. Islamic finance options important.' },
  { country_code: 'SG', country_name: 'Singapore', currency: 'SGD', primary_language: 'English', secondary_languages: ['Mandarin', 'Malay', 'Tamil'], timezone: 'Asia/Singapore', regulatory_context: 'Tax: IRAS. GST 9%. Corporate: ACRA. MAS for financial services. PDPA for data privacy.', market_context: 'Global financial hub. Finance, technology, trade, logistics. PayNow, NETS payments. ASEAN gateway.', agent_injection: 'Operating in Singapore. Currency SGD. English business language. World-class regulatory environment. PDPA data compliance required.' },
  { country_code: 'TH', country_name: 'Thailand', currency: 'THB', primary_language: 'Thai', secondary_languages: ['English'], timezone: 'Asia/Bangkok', regulatory_context: 'Tax: RD. VAT 7%. Corporate: DBD. BOT for banking.', market_context: 'Bangkok hub. Tourism, manufacturing, agriculture. PromptPay mobile payment system. Card payments common.', agent_injection: 'Operating in Thailand. Currency THB. Thai language important. Tourism and manufacturing economy. PromptPay widely used.' },
  { country_code: 'PH', country_name: 'Philippines', currency: 'PHP', primary_language: 'Filipino', secondary_languages: ['English'], timezone: 'Asia/Manila', regulatory_context: 'Tax: BIR. VAT 12%. Corporate: SEC. BSP for banking.', market_context: 'Manila hub. BPO sector, remittances, agriculture. GCash, Maya mobile payments. Highly digital youth population.', agent_injection: 'Operating in Philippines. Currency PHP. English widely used. GCash is primary mobile payment. Remittance market significant.' },
  { country_code: 'VN', country_name: 'Vietnam', currency: 'VND', primary_language: 'Vietnamese', secondary_languages: ['English'], timezone: 'Asia/Ho_Chi_Minh', regulatory_context: 'Tax: GDT. VAT 10%. Corporate: Business Registration. SBV for banking.', market_context: 'HCMC and Hanoi hubs. Manufacturing, agriculture, tourism. MoMo, VNPay mobile payments. Fast growing digital economy.', agent_injection: 'Operating in Vietnam. Currency VND. Vietnamese primary. Manufacturing and export economy. Digital payments growing rapidly.' },
  { country_code: 'BD', country_name: 'Bangladesh', currency: 'BDT', primary_language: 'Bengali', secondary_languages: ['English'], timezone: 'Asia/Dhaka', regulatory_context: 'Tax: NBR. VAT 15%. Corporate: RJSC. BB for banking.', market_context: 'Dhaka hub. RMG/textiles world leader, agriculture, remittances. bKash mobile money dominant.', agent_injection: 'Operating in Bangladesh. Currency BDT. Bengali primary. bKash is dominant payment. Textile industry focus.' },
  { country_code: 'LK', country_name: 'Sri Lanka', currency: 'LKR', primary_language: 'Sinhala', secondary_languages: ['Tamil', 'English'], timezone: 'Asia/Colombo', regulatory_context: 'Tax: IRD. VAT 18%. Corporate: ROC. CBSL for banking.', market_context: 'Colombo hub. Tourism, tea, apparel, IT services. Card and bank transfer common.', agent_injection: 'Operating in Sri Lanka. Currency LKR. English used in business. Tourism and apparel focus.' },
  { country_code: 'NP', country_name: 'Nepal', currency: 'NPR', primary_language: 'Nepali', secondary_languages: ['English'], timezone: 'Asia/Kathmandu', regulatory_context: 'Tax: IRD. VAT 13%. Corporate: OCR. NRB for banking.', market_context: 'Kathmandu hub. Tourism, remittances, agriculture. eSewa, Khalti mobile payments.', agent_injection: 'Operating in Nepal. Currency NPR. Nepali primary. Remittance economy. Mobile payments growing.' },
  { country_code: 'DE', country_name: 'Germany', currency: 'EUR', primary_language: 'German', secondary_languages: ['English'], timezone: 'Europe/Berlin', regulatory_context: 'Tax: Finanzamt. VAT 19%. Corporate: Handelsregister. BaFin for financial services. GDPR applies. Strong labour law.', market_context: 'Frankfurt, Munich, Berlin hubs. Manufacturing, engineering, automotive, finance. Bank transfer (SEPA) dominant. Formal business culture.', agent_injection: 'Operating in Germany. Currency EUR. German primary, English in international business. GDPR compliance critical. Very formal business culture. Punctuality essential.' },
  { country_code: 'FR', country_name: 'France', currency: 'EUR', primary_language: 'French', secondary_languages: ['English'], timezone: 'Europe/Paris', regulatory_context: 'Tax: DGFiP. VAT 20%. Corporate: INSEE/SIREN. AMF for financial services. GDPR applies.', market_context: 'Paris hub. Luxury goods, tourism, agriculture, aerospace, finance. Card payments, bank transfer. Formal business culture.', agent_injection: 'Operating in France. Currency EUR. French primary — always respond in French to French speakers. GDPR compliance required. Formal business culture.' },
  { country_code: 'NL', country_name: 'Netherlands', currency: 'EUR', primary_language: 'Dutch', secondary_languages: ['English'], timezone: 'Europe/Amsterdam', regulatory_context: 'Tax: Belastingdienst. VAT 21%. Corporate: KVK. AFM/DNB for financial services. GDPR applies.', market_context: 'Amsterdam hub. Trade, logistics, finance, agriculture. iDEAL payment dominant. English widely spoken.', agent_injection: 'Operating in Netherlands. Currency EUR. English widely used. iDEAL dominant payment. Direct business communication style.' },
  { country_code: 'ES', country_name: 'Spain', currency: 'EUR', primary_language: 'Spanish', secondary_languages: ['English', 'Catalan'], timezone: 'Europe/Madrid', regulatory_context: 'Tax: AEAT. VAT 21%. Corporate: Registro Mercantil. CNMV for financial services. GDPR applies.', market_context: 'Madrid and Barcelona hubs. Tourism, agriculture, real estate, automotive. Card payments common.', agent_injection: 'Operating in Spain. Currency EUR. Spanish primary. Relationship-driven business culture. Siesta culture affects working hours.' },
  { country_code: 'IT', country_name: 'Italy', currency: 'EUR', primary_language: 'Italian', secondary_languages: ['English'], timezone: 'Europe/Rome', regulatory_context: 'Tax: Agenzia Entrate. VAT 22%. Corporate: CCIAA. Consob for financial services. GDPR applies. E-invoicing mandatory.', market_context: 'Milan, Rome hubs. Fashion, food, manufacturing, tourism. Bank transfer and card common.', agent_injection: 'Operating in Italy. Currency EUR. Italian primary. E-invoicing mandatory. Relationship-driven business culture. Family business culture dominant.' },
  { country_code: 'PL', country_name: 'Poland', currency: 'PLN', primary_language: 'Polish', secondary_languages: ['English'], timezone: 'Europe/Warsaw', regulatory_context: 'Tax: KAS. VAT 23%. Corporate: KRS. KNF for financial services. GDPR applies.', market_context: 'Warsaw, Krakow hubs. Manufacturing, IT outsourcing, agriculture. BLIK payment dominant.', agent_injection: 'Operating in Poland. Currency PLN. Polish primary. BLIK payment system dominant. Growing tech sector.' },
  { country_code: 'SE', country_name: 'Sweden', currency: 'SEK', primary_language: 'Swedish', secondary_languages: ['English'], timezone: 'Europe/Stockholm', regulatory_context: 'Tax: Skatteverket. VAT 25%. Corporate: Bolagsverket. FI for financial services. GDPR applies.', market_context: 'Stockholm hub. Tech startups, manufacturing, clean energy. Swish payment dominant. Nearly cashless society.', agent_injection: 'Operating in Sweden. Currency SEK. English widely used in business. Swish payment dominant. Flat organisational culture. Sustainability important.' },
  { country_code: 'NO', country_name: 'Norway', currency: 'NOK', primary_language: 'Norwegian', secondary_languages: ['English'], timezone: 'Europe/Oslo', regulatory_context: 'Tax: Skatteetaten. VAT 25%. Corporate: Brønnøysund. Finanstilsynet for financial services.', market_context: 'Oslo hub. Oil and gas, shipping, seafood, sovereign wealth fund. Vipps payment. High cost of living.', agent_injection: 'Operating in Norway. Currency NOK. English widely used. Vipps payment. High-cost economy. Work-life balance culturally important.' },
  { country_code: 'DK', country_name: 'Denmark', currency: 'DKK', primary_language: 'Danish', secondary_languages: ['English'], timezone: 'Europe/Copenhagen', regulatory_context: 'Tax: SKAT. VAT 25%. Corporate: Erhvervsstyrelsen. Finanstilsynet for financial services. GDPR.', market_context: 'Copenhagen hub. Shipping, pharma, food, design. MobilePay dominant. Nearly cashless.', agent_injection: 'Operating in Denmark. Currency DKK. English widely used. MobilePay dominant. Flat business culture. Sustainability focus.' },
  { country_code: 'CH', country_name: 'Switzerland', currency: 'CHF', primary_language: 'German', secondary_languages: ['French', 'Italian', 'English'], timezone: 'Europe/Zurich', regulatory_context: 'Tax: ESTV. VAT 8.1%. Corporate: Handelsregister. FINMA for financial services. Strong data privacy.', market_context: 'Zurich, Geneva hubs. Finance, pharma, watchmaking, tourism. TWINT payment. Very high standards.', agent_injection: 'Operating in Switzerland. Currency CHF. Multilingual — detect language. FINMA regulation important. Precision and quality expectations very high.' },
  { country_code: 'BE', country_name: 'Belgium', currency: 'EUR', primary_language: 'Dutch', secondary_languages: ['French', 'German', 'English'], timezone: 'Europe/Brussels', regulatory_context: 'Tax: SPF Finances. VAT 21%. Corporate: BCE. FSMA for financial services. GDPR. EU headquarters.', market_context: 'Brussels hub. EU institutions, finance, chocolate, chemicals. Bancontact payment. Multilingual business.', agent_injection: 'Operating in Belgium. Currency EUR. Multilingual — detect language carefully. EU compliance important given Brussels location.' },
  { country_code: 'PT', country_name: 'Portugal', currency: 'EUR', primary_language: 'Portuguese', secondary_languages: ['English'], timezone: 'Europe/Lisbon', regulatory_context: 'Tax: AT. VAT 23%. Corporate: IRN. CMVM for financial services. GDPR. NHR tax regime for expats.', market_context: 'Lisbon and Porto hubs. Tourism, technology, real estate. MBWay payment. Growing tech startup scene.', agent_injection: 'Operating in Portugal. Currency EUR. Portuguese primary. Growing startup ecosystem. NHR tax regime attracts expats.' },
  { country_code: 'RU', country_name: 'Russia', currency: 'RUB', primary_language: 'Russian', secondary_languages: ['English'], timezone: 'Europe/Moscow', regulatory_context: 'Tax: FNS. VAT 20%. Corporate: FNS registration. CBR for banking. Data localisation laws apply.', market_context: 'Moscow and St Petersburg hubs. Energy, defence, agriculture, IT. Mir card, SBP payment. Sanctions affect international trade.', agent_injection: 'Operating in Russia. Currency RUB. Russian primary. Data must be stored locally per law. Sanctions compliance important.' },
  { country_code: 'BR', country_name: 'Brazil', currency: 'BRL', primary_language: 'Portuguese', secondary_languages: ['English'], timezone: 'America/Sao_Paulo', regulatory_context: 'Tax: Receita Federal. Complex multi-tier tax. Corporate: JUCESP. BCB for banking. LGPD data protection.', market_context: 'Sao Paulo financial hub. Agriculture, manufacturing, fintech. PIX instant payment dominant. LGPD data law.', agent_injection: 'Operating in Brazil. Currency BRL. Portuguese primary. PIX is the dominant payment system. Complex tax system — always recommend accountant.' },
  { country_code: 'MX', country_name: 'Mexico', currency: 'MXN', primary_language: 'Spanish', secondary_languages: ['English'], timezone: 'America/Mexico_City', regulatory_context: 'Tax: SAT. VAT 16%. Corporate: SAT registration. CNBV for financial services. CFDI e-invoicing mandatory.', market_context: 'Mexico City hub. Manufacturing, agriculture, tourism, nearshoring boom. SPEI, CoDi payments. NAFTA/USMCA trade.', agent_injection: 'Operating in Mexico. Currency MXN. Spanish primary. CFDI e-invoicing mandatory for all businesses. Nearshoring opportunity with US.' },
  { country_code: 'AR', country_name: 'Argentina', currency: 'ARS', primary_language: 'Spanish', secondary_languages: ['English'], timezone: 'America/Argentina/Buenos_Aires', regulatory_context: 'Tax: AFIP. Complex tax system with multiple rates. BCRA for banking. Currency controls active.', market_context: 'Buenos Aires hub. Agriculture, energy, technology. Currency volatility significant. DEBIN, Mercado Pago payments.', agent_injection: 'Operating in Argentina. Currency ARS. Spanish primary. Currency controls and volatility are major business factors. Always note USD parallel rate context.' },
  { country_code: 'CL', country_name: 'Chile', currency: 'CLP', primary_language: 'Spanish', secondary_languages: ['English'], timezone: 'America/Santiago', regulatory_context: 'Tax: SII. VAT 19%. Corporate: SII registration. CMF for financial services.', market_context: 'Santiago hub. Mining, agriculture, wine, fintech. Transbank, MACH payments. Most stable South American economy.', agent_injection: 'Operating in Chile. Currency CLP. Spanish primary. Most stable regulatory environment in South America. Copper mining economy.' },
  { country_code: 'CO', country_name: 'Colombia', currency: 'COP', primary_language: 'Spanish', secondary_languages: ['English'], timezone: 'America/Bogota', regulatory_context: 'Tax: DIAN. VAT 19%. Corporate: CCB registration. SFC for financial services.', market_context: 'Bogota hub. Coffee, manufacturing, technology, emeralds. Nequi, Daviplata mobile payments. Growing startup scene.', agent_injection: 'Operating in Colombia. Currency COP. Spanish primary. Growing tech ecosystem. Coffee and agriculture significant.' },
  { country_code: 'GH', country_name: 'Ghana', currency: 'GHS', primary_language: 'English', secondary_languages: ['Twi', 'Ga'], timezone: 'Africa/Accra', regulatory_context: 'Tax: GRA. VAT 15%. Corporate: ORC. BoG for banking.', market_context: 'Accra hub. Gold, cocoa, oil, services. MTN MoMo mobile money dominant. Stable West African democracy.', agent_injection: 'Operating in Ghana. Currency GHS. English primary. MTN Mobile Money dominant payment. Stable business environment.' },
  { country_code: 'MA', country_name: 'Morocco', currency: 'MAD', primary_language: 'Arabic', secondary_languages: ['French', 'Amazigh', 'English'], timezone: 'Africa/Casablanca', regulatory_context: 'Tax: DGI. VAT 20%. Corporate: RC registration. BAM for banking.', market_context: 'Casablanca hub. Tourism, phosphates, agriculture, automotive. CMI payment. Gateway between Africa and Europe.', agent_injection: 'Operating in Morocco. Currency MAD. Arabic and French used in business. Strategic Africa-Europe gateway. Tourism significant.' },
  { country_code: 'TZ', country_name: 'Tanzania', currency: 'TZS', primary_language: 'Swahili', secondary_languages: ['English'], timezone: 'Africa/Dar_es_Salaam', regulatory_context: 'Tax: TRA. VAT 18%. Corporate: BRELA. BoT for banking.', market_context: 'Dar es Salaam hub. Tourism, agriculture, gold. M-Pesa, Tigo Pesa mobile money. Growing economy.', agent_injection: 'Operating in Tanzania. Currency TZS. Swahili primary. M-Pesa dominant payment. Tourism and agriculture economy.' },
  { country_code: 'JP', country_name: 'Japan', currency: 'JPY', primary_language: 'Japanese', secondary_languages: ['English'], timezone: 'Asia/Tokyo', regulatory_context: 'Tax: NTA. Consumption tax 10%. Corporate: MOJ registration. FSA for financial services. APPI data privacy.', market_context: 'Tokyo hub. Technology, automotive, finance, robotics. IC card (Suica), PayPay payments. Cash still widely used.', agent_injection: 'Operating in Japan. Currency JPY. Japanese primary. Extremely formal business culture. Business cards exchanged ceremonially. Consensus-driven decisions. Punctuality critical.' },
  { country_code: 'KR', country_name: 'South Korea', currency: 'KRW', primary_language: 'Korean', secondary_languages: ['English'], timezone: 'Asia/Seoul', regulatory_context: 'Tax: NTS. VAT 10%. Corporate: CRO. FSC/FSS for financial services. PIPA data privacy.', market_context: 'Seoul hub. Technology, automotive, K-pop, cosmetics. KakaoPay, Samsung Pay, Naver Pay dominant.', agent_injection: 'Operating in South Korea. Currency KRW. Korean primary. Hierarchical business culture. KakaoTalk used for business communication. Technology-first market.' },
  { country_code: 'HK', country_name: 'Hong Kong', currency: 'HKD', primary_language: 'Cantonese', secondary_languages: ['English', 'Mandarin'], timezone: 'Asia/Hong_Kong', regulatory_context: 'Tax: IRD. Low tax: 16.5% profits, 15% salaries, no capital gains. Corporate: CR. SFC/HKMA for financial services.', market_context: 'Global financial hub. Finance, trade, logistics, tourism. Octopus, FPS payments. Gateway to China.', agent_injection: 'Operating in Hong Kong. Currency HKD. English and Cantonese used in business. Low tax jurisdiction. China gateway.' },
  { country_code: 'TW', country_name: 'Taiwan', currency: 'TWD', primary_language: 'Mandarin', secondary_languages: ['English', 'Taiwanese'], timezone: 'Asia/Taipei', regulatory_context: 'Tax: MOF. VAT 5%. Corporate: MOEA. FSC for financial services.', market_context: 'Taipei hub. Semiconductors, electronics, technology. LINE Pay, street payments. Technology manufacturing powerhouse.', agent_injection: 'Operating in Taiwan. Currency TWD. Mandarin primary. Semiconductor and electronics hub. Formal business culture.' },
  { country_code: 'IL', country_name: 'Israel', currency: 'ILS', primary_language: 'Hebrew', secondary_languages: ['English', 'Arabic'], timezone: 'Asia/Jerusalem', regulatory_context: 'Tax: ITA. VAT 17%. Corporate: Companies Registrar. ISA for financial services.', market_context: 'Tel Aviv hub. Cybersecurity, agriculture tech, biotech, startups. Bit payment app. Start-up Nation culture.', agent_injection: 'Operating in Israel. Currency ILS. Hebrew primary, English in tech business. Innovation culture. Shabbat observed Friday sunset to Saturday.' },
  { country_code: 'NZ', country_name: 'New Zealand', currency: 'NZD', primary_language: 'English', secondary_languages: ['Māori'], timezone: 'Pacific/Auckland', regulatory_context: 'Tax: IRD. GST 15%. Corporate: Companies Office. FMA for financial services. Privacy Act.', market_context: 'Auckland hub. Agriculture, tourism, tech. Eftpos, Paymark payments. Strong agricultural exports.', agent_injection: 'Operating in New Zealand. Currency NZD. English primary. Māori culture respected. Agricultural and tourism economy. Relaxed but professional business culture.' }
]
